FROM golang:1.20.2-alpine AS development

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . . 
ENV OWM_API_KEY 17b73389f09254768c7e64f78cc426c7


RUN go build -o /rest-platform

EXPOSE 8001



CMD [ "/rest-platform"]